members:
- name: Michael Snook
  github: michaelsnook
  org: OPEN

repositories:
- title: OPEN And Friends (this one)
  link: https://github.com/the-open/open-and-friends
  contact: michaelsnook
  description: this repository is just a list of people on the team and projects people are sharing
